eshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from shopind import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/',views.index),
    # url(r'^need/',include('need.urls')),
    url(r'^login/',views.logins),
    url(r'^logout/', views.logouts),
    url(r'^register/',views.register),
    url(r"^usercenter/",views.usercenter),
    url(r"reusercenter_redit/",views.usercenter_edit),
    url(r"reusercenter_repassword/",views.usercenter_repassword),
    url(r"search/", views.search),
]


# +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

need/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from need import views
urlpatterns = [
    # path(r'admin/', admin.site.urls),
    url(r'nindex/',views.nindex),
]

need/models.py
from django.db import models

# Create your models here.

shopind/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.auth.models import AbstractUser
# Create your models here.
#商品类别表
class 商品类别表(models.Model):
    名称 = models.CharField(max_length=50,unique=True)#商品类别最大长度为50，且是不可重复唯一值
    类别描述 = models.TextField(blank=True)#可以为空
    图片 =models.ImageField(upload_to="category",blank=True)#上传图片到category文件夹,可以为空

    class Meta:
        verbose_name = "商品类别表"
        verbose_name_plural = "商品类别表"
        db_table="商品类别表"
    def __str__(self):
        return  self.名称

#产品列表
class 产品列表(models.Model):
    产品名称 = models.CharField(max_length=50,unique=True)#产品类别最大长度为50，且是不可重复唯一值
    产品描述 = models.TextField(blank=True)#可以为空
    产品图片 =models.ImageField(upload_to="category",blank=True)#上传图片到category文件夹,可以为空
    所属类别=models.ForeignKey(商品类别表,on_delete=models.CASCADE)#关联商品类别表的外键，串联接，连坐。当上表删除某类别数据本表数据也将被删除
    价格=models.DecimalField(max_digits=10,decimal_places=2)#max_digits最大位数，decimal_places最大小数位
    库存=models.IntegerField(default=0)#默认值为零
    已上架=models.BooleanField(default=True)
    创建时间=models.DateTimeField(auto_now_add=True)#当创建商品时自动加上当时时间可手动更改
    修改时间=models.DateTimeField(auto_now_add=True)#当修改商品时自动加上当时时间
    class Meta:
        verbose_name = "产品列表"
        verbose_name_plural = "产品列表"
        db_table="产品列表"
        ordering =('-创建时间',)
    def __str__(self):
        return  self.产品名称
class 用户列表(models.Model):
    username=models.OneToOneField(User,on_delete=models.CASCADE)
    昵称=models.CharField(max_length=50,blank=True)
    生日=models.DateTimeField(blank=True,null=True)
    # 邮箱=models.EmailField()
    账户余额=models.DecimalField(default=0,max_digits=10,decimal_places=2)
    class Meta:
        verbose_name = "用户列表"
        verbose_name_plural = "用户列表"
        db_table="用户列表"
    def __str__(self):
        return  self.username.username


    # 订单号=models.IntegerField()
# class 购物车(models.Model):
#     num=models.IntegerField(default=1)
#     产品 = models.ForeignKey(产品列表,on_delete=models.CASCADE)
#     用户id=models.ForeignKey(用户列表,on_delete=models.)
#
#
#     class Meta:
#         verbose_name = "购物车"
#         verbose_name_plural = "购物车表"
#         db_table = "别购物车表"
#
#     def __str__(self):
#         return self.名称

need/views.py
from django.shortcuts import render

# Create your views here.
def nindex(request):
    return render(request,'nindex.html')

shopind/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth .forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .form import *
from .models import *
import os
# Create your views here.
def index(request):
    img_path=r"C:\Users\y\Desktop\graduation_project\mysite\eshop\static\image\img\270"
    img_list=os.listdir(img_path)
    context={"img":img_list}
    print(img_list)
    return  render(request,'index.html',context)

def logins(request):
    if request.method=="POST":
        user=authenticate(request,username=request.POST["username"],password=request.POST["password"])
        if user is None:
            return render(request,"login.html",{"错误":"用户名或密码错误"})
        else:
            login(request,user)

            print(user)
            return redirect(index)
    else:
        return  render(request,'login.html')
def logouts(request):
    logout(request)
    return render(request, 'index.html')
def register(request):
    if request.method=="POST":
        frome=自定义注册表单(request.POST)
        print(frome)
        if frome.is_valid():
            frome.save()
            user=authenticate(request, username=frome.cleaned_data["username"],password=frome.cleaned_data["password1"])
            user.email=frome.cleaned_data["email"]
            用户列表(username=user,昵称=frome.cleaned_data["昵称"],生日=frome.cleaned_data["生日"]).save()
            login(request,user)
            return redirect(index)

    else:
        frome=自定义注册表单()
    contexts={"register_form":frome}
    return render(request,"register.html",contexts)

@login_required(login_url="/login/")
def usercenter(request):
        # userinfo=用户列表.objects.get(request.)
        print("用户中心")
        context={"user":request.user}
        return render(request,"用户信息页.html",context)

@login_required(login_url="/login/")
def usercenter_edit(request):
    if request.method=="POST":
        frome=修改表单(request.POST,instance=request.user)
        print(frome)
        if frome.is_valid():
            frome.save()
            request.user.用户列表.昵称 = frome.cleaned_data["昵称"]
            request.user.用户列表.生日= frome.cleaned_data["生日"]
            request.user.用户列表.save()
            # user=authenticate(request, username=frome.cleaned_data["username"],password=frome.cleaned_data["password1"])
            # user.email=frome.cleaned_data["email"]
            # 用户列表(username=user,昵称=frome.cleaned_data["昵称"],生日=frome.cleaned_data["生日"]).save()
            return redirect(usercenter)
    else:
        userchange=修改表单(instance=request.user)
    context = {"changefome": userchange,"users":request.user}
    return render(request,"修改用户信息.html",context)

@login_required(login_url="/login/")
def usercenter_repassword(request):
    if request.method=="POST":
        frome=PasswordChangeForm(data=request.POST,user=request.user)
        print(frome)
        if frome.is_valid():
            frome.save()

            return redirect(logins)
    else:
        userchange=PasswordChangeForm(user=request.user)
    context = {"changefome": userchange,"users":request.user}
    return render(request,"修改密码.html",context)
def search(request):
    return render(request,"搜索页.html")

templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="keywords" content="{% block keyswords %}商城{% endblock keyswords %}">
    <style>
        *  {margin: 0;
        padding: 0;
    }
    </style>
    <title>{% block title %}title{% endblock title %}</title>
</head>
<body>
<header>
  <div class="one">
        <img src="/static/image/logo.png" class="logo">
        <form action="" class="search">
            <input type="text" value="" style="width: 180px;height: 30px; text-align: center;margin-left: 360px;"><button><submit>搜索</submit></button>
            <input type="hidden" value="">
        </form>
           {% block headers %}
        {% endblock %}
    </div>

<header>
</header>
{% include "header.html" %}

</header>
{% block body %}
{% endblock body %}

</body>
</html>

templates/header.html
{% load static %}
<style>
    *  {margin: 0;
        padding: 0;
    }
    .one{
        margin-left: 0px;
        height: 67px;
        width: 80%;
    }
     #header{
         width: 100%;
         height: 40px;
     }
    #header li{
        height: 20px;
        width: auto;
        text-align:center;
        background-color: #00abf0;
        padding: 8px;
        list-style: none;
        float: left;
    }
    .logo{
        margin: 0;
        float: left;
    }
    .search{

        {#padding-top: 20px;#}
        {#padding-left: 90px;#}
        margin-top:8px;

    }
    .search span{

        text-align:center;
        {#background-color: #00abf0;#}
    }
</style>
<header>


    <div id="header">
        <ol>
            <li>主题市场</li>
            <li>女装</li>
            <li>男装</li>
            <li>内衣</li>
            <li>鞋靴</li>
            <li>箱包</li>
            <li>配件</li>
            <li>童装玩具</li>
            <li>孕产</li>
            <li>用品</li>
            <li>家电</li>
            <li>数码</li>
            <li>手机</li>
            <li>美妆</li>
            <li>洗护</li>
            <li>保健品</li>
            <li>珠宝</li>
            <li>眼镜</li>
            <li>手表</li>
            <li>运动</li>
            <li>户外</li>
            <li>乐器</li>
            <li>游戏</li>
            <li>动漫</li>
            <li>影视</li>
            <li>美食</li>
        </ol>
    </div>
</header>

templates/index.html
{% extends "base.html" %}
{% block title %}首页{% endblock title %}

{% block headers %}
        {% if user.is_authenticated %}
            <a href="/logout/">退出</a>
            <a href="/usercenter/">用户中心</a>
            <a href="/usercenter/"></a>
        {% else %}
                <a href="/login/">登陆</a>
        {% endif %}

{% endblock %}
{% block body %}
     <style>
    .list {

        margin-left: 162px;
    }
        .list li{
            border:1px solid  #999999 ;
            list-style-type: none;

            float:left ;
        }
     .header{
         margin-top:10px;
     }
    </style>

    <div>
        <img src="/static/image/datu.jpg" style="margin-left:250px">
    </div>
    <div>
        <img src="/static/image/gg.jpg">
    </div>
    <div class="list">
        <p>猜你喜欢</p>
        <ul>
            {% for im in img %}
            <li><img src="/static/image/img/270/{{ im }}"></li>
            {% endfor %}
        </ul>
    </div>
{% endblock body %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>


<style>
form{padding:0px 15px 15px 120px;}
form{width:500px;height:300px;}
form fieldset{border:0;align:center;}
form label{display:inline-block;width:60px;text-align:right}
input{width:240px;height:30px;}
#submit{width:200px;height:35px;position:relative;left:70px;}
#submit:hover{
		cursor: pointer;
		background:#D8D8D8;
	}
body{
	width:100%;
    height:100%;
	background: #E9E9E9;
	}
#box{position:fixed;left:0px;right:0px;width:706px;margin-left:auto;margin-right:auto;top:100px;}
#code{width: 70px;
	 height: 40px;
     font-size:18px;}
	#captcha_img{
    position:relative;
	bottom:-15px;
	}
a{position:relative;bottom:-10px;}
</style>

<body>
  <div id="box">

    <form method="post"action="login.html"style="background:#00abf0">
        <a href="/index/">回到首页</a>
        {% csrf_token %}
    <fieldset>
     {{ 错误 }}
      <p>
        <label>用户名:</label>
        <input type="text"name="username"placeholder="用户名"required="required"/>
      </p>
      <p>
        <label>密码:</label>
        <input type="password"name="password"placeholder="密码"required="required"/>
      </p>
{#      <p>#}
{#        <label>验证码:</label>#}
{#        <input type="text"name="authcode"value=""required="required" id="code"/>#}
{#        <img id="captcha_img"src="idcode.php"/>#}
{#        <a href="javascript:void(0)"onclick="document.getElementById('captcha_img').src='idcode.php'">看不清</a><!-- javascript:void(0)是一个死链接不会跳转也不会返回到顶部. -->#}
{#      </p>#}
{#      <p>#}
        <a href="/register/">没注册</a>
      </p>
      <p>
        <input type="submit"value="登陆"name="submit" id="submit"/>
      </p>
    </fieldset>
    </form>
  </div>
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/lunbo.html
<link type="text/css" rel="stylesheet" href="/static/css/style.css">

</head>
<body>

<section class="pc-banner">
	<div class="swiper-container">
		<div class="swiper-wrapper">
			<div class="swiper-slide swiper-slide-center none-effect">
				<a href="#">
					<img src="img/banner001.jpg">
				</a>
				<div class="layer-mask"></div>
			</div>
			<div class="swiper-slide">
				<a href="#">
					<img src="img/banner002.jpg">
				</a>
				<div class="layer-mask"></div>
			</div>
			<div class="swiper-slide">
				<a href="#">
					<img src="img/banner003.jpg">
				</a>
				<div class="layer-mask"></div>
			</div>
			<div class="swiper-slide">
				<a href="#">
					<img src="img/banner004.jpg">
				</a>
				<div class="layer-mask"></div>
			</div>
			<div class="swiper-slide">
				<a href="#">
					<img src="img/banner005.jpg">
				</a>
				<div class="layer-mask"></div>
			</div>
		</div>
		<div class="button">
			<div class="swiper-button-prev"></div>
			<div class="swiper-button-next"></div>
		</div>
	</div>
</section>
<script type="text/javascript" src="js/swiper.min.js"></script>
<script type="text/javascript">

	window.onload = function() {
		var swiper = new Swiper('.swiper-container',{
			autoplay: false,
			speed: 1000,
			autoplayDisableOnInteraction: false,
			loop: true,
			centeredSlides: true,
			slidesPerView: 2,
			pagination: '.swiper-pagination',
			paginationClickable: true,
			prevButton: '.swiper-button-prev',
			nextButton: '.swiper-button-next',
			onInit: function(swiper) {
				swiper.slides[2].className = "swiper-slide swiper-slide-active";
			},
			breakpoints: {
				668: {
					slidesPerView: 1,
				}
			}
		});
	}


</script>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>regiater</title>
</head>
<body style="background-image: url('/static/image/rbg.jpg')">
<div style="margin-left: 420px">
<form method="post" action="/register/">
     {% csrf_token %}
      {% if register_form %}
        <p>{{ register_form.errors }}</p>
    {% endif %}

        <p></p>


{#    <input type="hidden" name="csrfmiddlewaretoken" value="IiWuzesccOoLnUOwPGhFVcn5Jnqlc3SMA0LvEhZYSS2fjVggmq9oW0cMsj0OSbXL">#}
    <p><label for="id_username">用户名:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username"> <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span></p>
<p><label for="id_password1">密码:</label> <input type="password" name="password1" required id="id_password1"> <span class="helptext"><ul><li>你的密码不能与其他个人信息太相似。</li><li>你的密码必须包含至少 8 个字符。</li><li>你的密码不能是大家都爱用的常见密码。</li><li>你的密码不能全部为数字。</li></ul></span></p>
<p><label for="id_password2">密码确认:</label> <input type="password" name="password2" required id="id_password2"> <span class="helptext">为了校验，请输入与上面相同的密码。</span></p>
<p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
<p><label for="id_昵称">昵称:</label> <input type="text" name="昵称" maxlength="50" id="id_昵称"></p>
<p><label for="id_生日">生日:</label> <input type="date" name="生日" id="id_生日"></p>

    <button type="submit">注册</button>
</form>
</div>
</body>
</html>

templates/修改密码.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    修改用户信息
{% endblock %}
{% block headers %}
      <a href="/index/">回到主页</a>
    <a href="/usercenter/">个人中心</a>
    <a href="#">充值</a>
    <a href="/reusercenter_redit/">修改用户信息</a>
{% endblock %}
{% block body %}

    <div>
    <form action="/reusercenter_redit/" method="post">
         {% csrf_token %}
          {% if changefome.errors %}
        <p>{{ changefome.errors }}</p>
        {% endif %}
        {{ changefome.as_p }}

{#       <p><label for="id_username">用户名:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username" value="{{ user.username }}"> <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span></p>#}
{#<p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" maxlength="254" id="id_email" value="{{ user.email }}"></p>#}
{#<p><label for="id_昵称">昵称:</label> <input type="text" name="昵称" maxlength="50" id="id_昵称" value="{{ user.用户列表.昵称 }}"></p>#}
{#<p><label for="id_生日">生日:</label> <input type="date" name="生日" id="id_生日" value="{{ user.用户列表.生日 }}"></p>#}
        <button type="submit">提交</button>
    </form>
    </div>
{% endblock %}

templates/修改用户信息.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    修改用户信息
{% endblock %}
{% block headers %}
      <a href="/index/">回到主页</a>
    <a href="/usercenter/">个人中心</a>
    <a href="#">充值</a>
    <a href="/reusercenter_repassword/">修改密码</a>
{% endblock %}
{% block body %}

    <div>
    <form action="/reusercenter_redit/" method="post">
         {% csrf_token %}
          {% if changefome.errors %}
        <p>{{ changefome.errors }}</p>
        {% endif %}
        <p><label for="id_username">用户名:</label> <input type="text" name="username" value="{{ users.username }}" maxlength="150" required id="id_username"> <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span></p>
        <p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" value="{{ users.email }}" maxlength="254" id="id_email"></p>
        <p><label for="id_昵称">昵称:</label> <input type="text" name="昵称" maxlength="50" id="id_昵称"></p>
        <p><label for="id_生日">生日:</label> <input type="date" name="生日" id="id_生日"></p>

{#       <p><label for="id_username">用户名:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username" value="{{ user.username }}"> <span class="helptext">必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。</span></p>#}
{#<p><label for="id_email">电子邮件地址:</label> <input type="email" name="email" maxlength="254" id="id_email" value="{{ user.email }}"></p>#}
{#<p><label for="id_昵称">昵称:</label> <input type="text" name="昵称" maxlength="50" id="id_昵称" value="{{ user.用户列表.昵称 }}"></p>#}
{#<p><label for="id_生日">生日:</label> <input type="date" name="生日" id="id_生日" value="{{ user.用户列表.生日 }}"></p>#}
        <button type="submit">提交</button>
    </form>
    </div>
{% endblock %}

templates/搜索页.html
{% extends "base.html" %}
{% load static %}

templates/用户信息页.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    用户中心
{% endblock %}
{% block headers %}
     <a href="/index/">回到主页</a>
    <a href="#">充值</a>
    <a href="/reusercenter_repassword/">修改密码</a>
    <a href="/reusercenter_redit/">修改用户信息</a>
{% endblock %}
{% block body %}

    <div>
        <p>用户名：{{ user.username }}</p>
        <p>邮箱：{{ user.email }}</p>
        <p>生日：{{ user.用户列表.生日 }}</p>
        <p>昵称：{{ user.用户列表.昵称 }}</p>
        <p>余额：{{ user.用户列表.余额 }}</p>
    </div>
{% endblock %}

templates/详情页.html
{% extends "base.html" %}
{% load static %}

templates/购物车.html
{% extends "base.html" %}
{% load static %}

备份文件/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
<div align="">
<form action="login.html" method="post">

    用户名：<input type="text" value="请输入用户名" name="username"><br />
    密码：<input type="password" value="请输入密码" name="password">

</form>
</div>
</body>
</html>

备份文件/templates/nindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>网站需求分析及说明</title>
</head>
<body>
<ol>
    <li>
        <h4>表名说明</h4>
        <ul>
            <li>test：练手测试专用表，数据无关仅要</li>
        </ul>
    </li>
    <li>
        <h4 >字段说明</h4>
        <ul>
            <li></li>
        </ul>
    </li>
</ol>
</body>
</html>